### ISSUE TITLE
ansi character test failed when file name starts with '-'

### ISSUE THREAD

**Issue by keedi** [abraxxa/Test-Portability-Files#1]
Hi,

In the perlport document:

```
The portable filename characters as defined by ANSI C are

a b c d e f g h i j k l m n o p q r t u v w x y z
A B C D E F G H I J K L M N O P Q R T U V W X Y Z
0 1 2 3 4 5 6 7 8 9
_ -

and the "-" shouldn't be the first character.
```

IMHO the file whch start with `_` is correct, but current version of this module consider this as invalid.

https://github.com/abraxxa/Test-Portability-Files/blob/master/lib/Test/Portability/Files.pm#L340

**Comment by abraxxa** [comment]
Fixed by #5.
