### ISSUE TITLE
Anything in particular you'd like me to take a crack at?

### ISSUE THREAD

**Issue by tsibley** [abraxxa/Test-Portability-Files#2]
Hi there,

I'm assigned this distribution as part of the CPAN PR Challenge for the month of February.  Is there anything in particular you'd like me to hack on?

Cheers!

**Comment by abraxxa** [comment]
Sorry for not responding in time!
I took over the module myself as it was in need for a maintainer and just applied all outstanding pull-requests to fix the open issues.
Nevertheless thank you for the offer!
